### PR TITLE
docs(examples): add flash tutorials to spi related examples

### PR DESCRIPTION
**Pull request by NanaHigh**
- add flash tutorials to `spi-demo`, `sdcard-demo`, `sdcard-gpt-demo`
- add `blri` command, use `blri` by `cargo blri <file_path>`

### CODE REVIEW

**Review by Placebo27 — APPROVED** [review]
LGTM! Every flash tutorial match each example.

**Review by luojia65 — APPROVED** [review]
Code style LGTM

**Comment by Placebo27** [comment]
Please adhere the test results, need the picture of two adapter board plug sequence transfer and screenshot of serial port output to prove that the test is no problem, thx.

**Comment by NanaHigh** [comment]
Tested on M1sdock, all examples work well.
Adapter boards:
plug1
plug2
plug3
Pinout:
pin
Results:
- `spi-demo`
spi-demo
- `sdcard-demo`
sdcard-demo
- `sdcard-gpt-demo`
sdcard-gpt-demo

**Pull request merged**
